module ram_wrap #(
    parameter DATA_WIDTH = 18,  // 1, 2, 4, 9, 18, 36
    parameter ADDR_WIDTH = 10   // must match depth: 14,13,12,11,10,9 respectively
) (
    input  wire                  clk,
    input  wire [ADDR_WIDTH-1:0] wr_addr,
    input  wire [ADDR_WIDTH-1:0] rd_addr,
    input  wire [DATA_WIDTH-1:0] din,
    output wire [DATA_WIDTH-1:0] dout,
    input  wire                  wr_en,
    input  wire                  rd_en,
    input  wire                  rst
);

  localparam int EBR_WIDTH =
    (DATA_WIDTH == 1 ) ? 1  :
    (DATA_WIDTH == 2 ) ? 2  :
    (DATA_WIDTH <= 4 ) ? 4  :
    (DATA_WIDTH <= 9 ) ? 9  :
    (DATA_WIDTH <= 18) ? 18 :
    (DATA_WIDTH <= 36) ? 36 :
    -1;

  wire [35:0] dia = {{(36 - DATA_WIDTH) {1'b0}}, din};

  wire [35:0] dob;

  assign dout = dob[DATA_WIDTH-1:0];

  localparam EBR_AW =
    (DATA_WIDTH == 1 ) ? 14 :
    (DATA_WIDTH == 2 ) ? 13 :
    (DATA_WIDTH <= 4 ) ? 12 :
    (DATA_WIDTH <= 9 ) ? 11 :
    (DATA_WIDTH <= 18) ? 10 :
    (DATA_WIDTH <= 36) ? 9  :
    -1;

  if (EBR_WIDTH == -1 || EBR_AW == -1) $error("fail");

  wire [13:0] ada_w = {{(14 - ADDR_WIDTH) {1'b0}}, wr_addr};
  wire [13:0] adb_r = {{(14 - ADDR_WIDTH) {1'b0}}, rd_addr};

  // -----------------------------------------------------------------------
  // Primitive instantiation
  // -----------------------------------------------------------------------
  generate

    if (EBR_WIDTH == 1) begin
      DP16KD #(
          .DATA_WIDTH_A(EBR_WIDTH),
          .DATA_WIDTH_B(EBR_WIDTH),
          .REGMODE_A   ("NOREG"),
          .REGMODE_B   ("NOREG"),
          .RESETMODE   ("SYNC"),
          .GSR         ("DISABLED")
      ) EBR_INST (
          .DIA0 (dia[0]),
          .ADA0 (ada_w[0]),
          .ADA1 (ada_w[1]),
          .ADA2 (ada_w[2]),
          .ADA3 (ada_w[3]),
          .ADA4 (ada_w[4]),
          .ADA5 (ada_w[5]),
          .ADA6 (ada_w[6]),
          .ADA7 (ada_w[7]),
          .ADA8 (ada_w[8]),
          .ADA9 (ada_w[9]),
          .ADA10(ada_w[10]),
          .ADA11(ada_w[11]),
          .ADA12(ada_w[12]),
          .ADA13(ada_w[13]),
          .ADB0 (adb_r[0]),
          .ADB1 (adb_r[1]),
          .ADB2 (adb_r[2]),
          .ADB3 (adb_r[3]),
          .ADB4 (adb_r[4]),
          .ADB5 (adb_r[5]),
          .ADB6 (adb_r[6]),
          .ADB7 (adb_r[7]),
          .ADB8 (adb_r[8]),
          .ADB9 (adb_r[9]),
          .ADB10(adb_r[10]),
          .ADB11(adb_r[11]),
          .ADB12(adb_r[12]),
          .ADB13(adb_r[13]),
          .CEA  (wr_en),
          .CLKA (clk),
          .WEA  (1'b1),
          .CSA0 (1'b1),
          .CSA1 (1'b0),
          .CSA2 (1'b0),
          .RSTA (rst),
          .OCEA (1'b0),

          .CEB (rd_en),
          .CLKB(clk),
          .WEB (1'b0),
          .CSB0(1'b1),
          .CSB1(1'b0),
          .CSB2(1'b0),
          .RSTB(rst),
          .OCEB(1'b0),

          .DOB0(dob[0])
      );
    end else if (EBR_WIDTH == 2) begin
      DP16KD #(
          .DATA_WIDTH_A(EBR_WIDTH),
          .DATA_WIDTH_B(EBR_WIDTH),
          .REGMODE_A   ("NOREG"),
          .REGMODE_B   ("NOREG"),
          .RESETMODE   ("SYNC"),
          .GSR         ("DISABLED")
      ) EBR_INST (
          .DIA0 (dia[0]),
          .DIA1 (dia[1]),
          .ADA0 (ada_w[0]),
          .ADA1 (ada_w[1]),
          .ADA2 (ada_w[2]),
          .ADA3 (ada_w[3]),
          .ADA4 (ada_w[4]),
          .ADA5 (ada_w[5]),
          .ADA6 (ada_w[6]),
          .ADA7 (ada_w[7]),
          .ADA8 (ada_w[8]),
          .ADA9 (ada_w[9]),
          .ADA10(ada_w[10]),
          .ADA11(ada_w[11]),
          .ADA12(ada_w[12]),
          .ADB0 (adb_r[0]),
          .ADB1 (adb_r[1]),
          .ADB2 (adb_r[2]),
          .ADB3 (adb_r[3]),
          .ADB4 (adb_r[4]),
          .ADB5 (adb_r[5]),
          .ADB6 (adb_r[6]),
          .ADB7 (adb_r[7]),
          .ADB8 (adb_r[8]),
          .ADB9 (adb_r[9]),
          .ADB10(adb_r[10]),
          .ADB11(adb_r[11]),
          .ADB12(adb_r[12]),
          .CEA  (wr_en),
          .CLKA (clk),
          .WEA  (1'b1),
          .CSA0 (1'b0),
          .CSA1 (1'b0),
          .CSA2 (1'b0),
          .RSTA (rst),
          .OCEA (1'b0),

          .CEB (rd_en),
          .CLKB(clk),
          .WEB (1'b0),
          .CSB0(1'b0),
          .CSB1(1'b0),
          .CSB2(1'b0),
          .RSTB(rst),
          .OCEB(1'b0),

          .DOB0(dob[0]),
          .DOB1(dob[1])
      );
    end else if (EBR_WIDTH == 4) begin
      DP16KD #(
          .DATA_WIDTH_A(EBR_WIDTH),
          .DATA_WIDTH_B(EBR_WIDTH),
          .REGMODE_A   ("NOREG"),
          .REGMODE_B   ("NOREG"),
          .RESETMODE   ("SYNC"),
          .GSR         ("DISABLED")
      ) EBR_INST (
          .DIA0 (dia[0]),
          .DIA1 (dia[1]),
          .DIA2 (dia[2]),
          .DIA3 (dia[3]),
          .ADA0 (ada_w[0]),
          .ADA1 (ada_w[1]),
          .ADA2 (ada_w[2]),
          .ADA3 (ada_w[3]),
          .ADA4 (ada_w[4]),
          .ADA5 (ada_w[5]),
          .ADA6 (ada_w[6]),
          .ADA7 (ada_w[7]),
          .ADA8 (ada_w[8]),
          .ADA9 (ada_w[9]),
          .ADA10(ada_w[10]),
          .ADA11(ada_w[11]),
          .ADB0 (adb_r[0]),
          .ADB1 (adb_r[1]),
          .ADB2 (adb_r[2]),
          .ADB3 (adb_r[3]),
          .ADB4 (adb_r[4]),
          .ADB5 (adb_r[5]),
          .ADB6 (adb_r[6]),
          .ADB7 (adb_r[7]),
          .ADB8 (adb_r[8]),
          .ADB9 (adb_r[9]),
          .ADB10(adb_r[10]),
          .ADB11(adb_r[11]),
          .CEA  (wr_en),
          .CLKA (clk),
          .WEA  (1'b1),
          .CSA0 (1'b0),
          .CSA1 (1'b0),
          .CSA2 (1'b0),
          .RSTA (rst),
          .OCEA (1'b0),

          .CEB (rd_en),
          .CLKB(clk),
          .WEB (1'b0),
          .CSB0(1'b0),
          .CSB1(1'b0),
          .CSB2(1'b0),
          .RSTB(rst),
          .OCEB(1'b0),

          .DOB0(dob[0]),
          .DOB1(dob[1]),
          .DOB2(dob[2]),
          .DOB3(dob[3])
      );
    end else if (EBR_WIDTH == 9) begin
      DP16KD #(
          .DATA_WIDTH_A(EBR_WIDTH),
          .DATA_WIDTH_B(EBR_WIDTH),
          .REGMODE_A   ("NOREG"),
          .REGMODE_B   ("NOREG"),
          .RESETMODE   ("SYNC")
      ) EBR_INST (
          .DIA0 (dia[0]),
          .DIA1 (dia[1]),
          .DIA2 (dia[2]),
          .DIA3 (dia[3]),
          .DIA4 (dia[4]),
          .DIA5 (dia[5]),
          .DIA6 (dia[6]),
          .DIA7 (dia[7]),
          .DIA8 (dia[8]),
          .DIA9 ('0),
          .DIA10('0),
          .DIA11('0),
          .DIA12('0),
          .DIA13('0),
          .DIA14('0),
          .DIA15('0),
          .DIA16('0),
          .DIA17('0),
          .ADA0 (1'b0),
          .ADA1 (1'b0),
          .ADA2 (1'b0),
          .ADA3 (ada_w[0]),
          .ADA4 (ada_w[1]),
          .ADA5 (ada_w[2]),
          .ADA6 (ada_w[3]),
          .ADA7 (ada_w[4]),
          .ADA8 (ada_w[5]),
          .ADA9 (ada_w[6]),
          .ADA10(ada_w[7]),
          .ADA11(ada_w[8]),
          .ADA12(ada_w[9]),
          .ADA13(ada_w[10]),
          .ADB0 (1'b0),
          .ADB1 (1'b0),
          .ADB2 (1'b0),
          .ADB3 (adb_r[0]),
          .ADB4 (adb_r[1]),
          .ADB5 (adb_r[2]),
          .ADB6 (adb_r[3]),
          .ADB7 (adb_r[4]),
          .ADB8 (adb_r[5]),
          .ADB9 (adb_r[6]),
          .ADB10(adb_r[7]),
          .ADB11(adb_r[8]),
          .ADB12(adb_r[9]),
          .ADB13(adb_r[10]),
          .CEA  (wr_en),
          .CLKA (clk),
          .WEA  (1'b1),
          .CSA0 (1'b0),
          .CSA1 (1'b0),
          .CSA2 (1'b0),
          .RSTA (rst),
          .OCEA (1'b0),

          .CEB (rd_en),
          .CLKB(clk),
          .WEB (1'b0),
          .CSB0(1'b0),
          .CSB1(1'b0),
          .CSB2(1'b0),
          .RSTB(rst),
          .OCEB(1'b0),

          .DOB0(dob[0]),
          .DOB1(dob[1]),
          .DOB2(dob[2]),
          .DOB3(dob[3]),
          .DOB4(dob[4]),
          .DOB5(dob[5]),
          .DOB6(dob[6]),
          .DOB7(dob[7]),
          .DOB8(dob[8])
      );
    end else if (EBR_WIDTH == 18) begin
      DP16KD #(
          .DATA_WIDTH_A(EBR_WIDTH),
          .DATA_WIDTH_B(EBR_WIDTH),
          .REGMODE_A   ("NOREG"),
          .REGMODE_B   ("NOREG"),
          .RESETMODE   ("SYNC"),
          .GSR         ("ENABLED")
      ) EBR_INST (
          .DIA0 (dia[0]),
          .DIA1 (dia[1]),
          .DIA2 (dia[2]),
          .DIA3 (dia[3]),
          .DIA4 (dia[4]),
          .DIA5 (dia[5]),
          .DIA6 (dia[6]),
          .DIA7 (dia[7]),
          .DIA8 (dia[8]),
          .DIA9 (dia[9]),
          .DIA10(dia[10]),
          .DIA11(dia[11]),
          .DIA12(dia[12]),
          .DIA13(dia[13]),
          .DIA14(dia[14]),
          .DIA15(dia[15]),
          .DIA16(dia[16]),
          .DIA17(dia[17]),
          .DIA18(dia[18]),
          .ADA0 (ada_w[0]),
          .ADA1 (ada_w[1]),
          .ADA2 (ada_w[2]),
          .ADA3 (ada_w[3]),
          .ADA4 (ada_w[4]),
          .ADA5 (ada_w[5]),
          .ADA6 (ada_w[6]),
          .ADA7 (ada_w[7]),
          .ADA8 (ada_w[8]),
          .ADA9 (ada_w[9]),
          .ADB0 (adb_r[0]),
          .ADB1 (adb_r[1]),
          .ADB2 (adb_r[2]),
          .ADB3 (adb_r[3]),
          .ADB4 (adb_r[4]),
          .ADB5 (adb_r[5]),
          .ADB6 (adb_r[6]),
          .ADB7 (adb_r[7]),
          .ADB8 (adb_r[8]),
          .ADB9 (adb_r[9]),
          .CEA  (wr_en),
          .CLKA (clk),
          .WEA  (1'b1),
          .CSA0 (1'b0),
          .CSA1 (1'b0),
          .CSA2 (1'b0),
          .RSTA (rst),
          .OCEA (1'b0),

          .CEB (rd_en),
          .CLKB(clk),
          .WEB (1'b0),
          .CSB0(1'b0),
          .CSB1(1'b0),
          .CSB2(1'b0),
          .RSTB(rst),
          .OCEB(1'b0),

          .DOB0 (dob[0]),
          .DOB1 (dob[1]),
          .DOB2 (dob[2]),
          .DOB3 (dob[3]),
          .DOB4 (dob[4]),
          .DOB5 (dob[5]),
          .DOB6 (dob[6]),
          .DOB7 (dob[7]),
          .DOB8 (dob[8]),
          .DOB9 (dob[9]),
          .DOB10(dob[10]),
          .DOB11(dob[11]),
          .DOB12(dob[12]),
          .DOB13(dob[13]),
          .DOB14(dob[14]),
          .DOB15(dob[15]),
          .DOB16(dob[16]),
          .DOB17(dob[17]),
          .DOB18(dob[18])
      );
    end else if (EBR_WIDTH == 36) begin
      PDPW16KD #(
          .REGMODE("NOREG"),
          .DATA_WIDTH_R(EBR_WIDTH),
          .DATA_WIDTH_W(EBR_WIDTH)
      ) ebr_NOREG_NOREG (
          .DI0  (dia[0]),
          .DI1  (dia[1]),
          .DI2  (dia[2]),
          .DI3  (dia[3]),
          .DI4  (dia[4]),
          .DI5  (dia[5]),
          .DI6  (dia[6]),
          .DI7  (dia[7]),
          .DI8  (dia[8]),
          .DI9  (dia[9]),
          .DI10 (dia[10]),
          .DI11 (dia[11]),
          .DI12 (dia[12]),
          .DI13 (dia[13]),
          .DI14 (dia[14]),
          .DI15 (dia[15]),
          .DI16 (dia[16]),
          .DI17 (dia[17]),
          .DI18 (dia[18]),
          .DI19 (dia[19]),
          .DI20 (dia[20]),
          .DI21 (dia[21]),
          .DI22 (dia[22]),
          .DI23 (dia[23]),
          .DI24 (dia[24]),
          .DI25 (dia[25]),
          .DI26 (dia[26]),
          .DI27 (dia[27]),
          .DI28 (dia[28]),
          .DI29 (dia[29]),
          .DI30 (dia[30]),
          .DI31 (dia[31]),
          .DI32 (dia[32]),
          .DI33 (dia[33]),
          .DI34 (dia[34]),
          .DI35 (dia[35]),
          .ADW0 (ada_w[0]),
          .ADW1 (ada_w[1]),
          .ADW2 (ada_w[2]),
          .ADW3 (ada_w[3]),
          .ADW4 (ada_w[4]),
          .ADW5 (ada_w[5]),
          .ADW6 (ada_w[6]),
          .ADW7 (ada_w[7]),
          .ADW8 (ada_w[8]),
          .ADR0 (1'b0),
          .ADR1 (1'b0),
          .ADR2 (1'b0),
          .ADR3 (1'b0),
          .ADR4 (1'b0),
          .ADR5 (adb_r[0]),
          .ADR6 (adb_r[1]),
          .ADR7 (adb_r[2]),
          .ADR8 (adb_r[3]),
          .ADR9 (adb_r[4]),
          .ADR10(adb_r[5]),
          .ADR11(adb_r[6]),
          .ADR12(adb_r[7]),
          .ADR13(adb_r[8]),
          // DO0 is from DI18
          .DO0  (dob[18]),
          .DO1  (dob[19]),
          .DO2  (dob[20]),
          .DO3  (dob[21]),
          .DO4  (dob[22]),
          .DO5  (dob[23]),
          .DO6  (dob[24]),
          .DO7  (dob[25]),
          .DO8  (dob[26]),
          .DO9  (dob[27]),
          .DO10 (dob[28]),
          .DO11 (dob[29]),
          .DO12 (dob[30]),
          .DO13 (dob[31]),
          .DO14 (dob[32]),
          .DO15 (dob[33]),
          .DO16 (dob[34]),
          .DO17 (dob[35]),
          .DO18 (dob[0]),
          .DO19 (dob[1]),
          .DO20 (dob[2]),
          .DO21 (dob[3]),
          .DO22 (dob[4]),
          .DO23 (dob[5]),
          .DO24 (dob[6]),
          .DO25 (dob[7]),
          .DO26 (dob[8]),
          .DO27 (dob[9]),
          .DO28 (dob[10]),
          .DO29 (dob[11]),
          .DO30 (dob[12]),
          .DO31 (dob[13]),
          .DO32 (dob[14]),
          .DO33 (dob[15]),
          .DO34 (dob[16]),
          .DO35 (dob[17]),

          .CEW (wr_en),
          .CLKW(clk),

          .CER (rd_en),
          .OCER(1'b0),
          .CLKR(clk),
          .RST (1'b0),
          // Unused: bank addressing
          .BE3 (1'b1),
          .BE2 (1'b1),
          .BE1 (1'b1),
          .BE0 (1'b1),
          // Unused: for > 18kb of memory
          .CSW2(1'b0),
          .CSW1(1'b0),
          .CSW0(1'b0),
          .CSR2(1'b0),
          .CSR1(1'b0),
          .CSR0(1'b0)
      );

    end

  endgenerate
endmodule

